### ISSUE TITLE
FoF Formatting ext

### ISSUE THREAD

**Issue by northeaster** [jslirola/flarum-ext-login2seeplus#2]
Can you make it fully compatible with the **FoF Formatting** ext? Let me give you an example: I shared a google drive link while the **MediaEmbed** option was active. Google drive link preview shows. It does not hide to guests.

![image](https://user-images.githubusercontent.com/55854510/87396832-1b412880-c5bc-11ea-8cf4-19e7aa7ae265.png)

**Comment by jslirola** [comment]
Take a look at the latest version and let me know if everything works.

https://github.com/jslirola/flarum-ext-login2seeplus/releases/tag/v0.1.5-beta

**Comment by northeaster** [comment]
How do I install this version on my site?

**Comment by jslirola** [comment]
You're right, I didn't see those empty lines using legacy mode. It should be fixed now.

```
composer update jslirola/flarum-ext-login2seeplus
php flarum cache:clear
```

**Comment by northeaster** [comment]
https://media.discordapp.net/attachments/593879341230850048/735918317386072214/unknown.png
&
https://media.discordapp.net/attachments/593879341230850048/735921550175240342/unknown.png

The extension works perfectly now. Thank you.

**Comment by northeaster** [comment]
If you want, you can update the issue as resolved.

**Comment by jslirola** [comment]
Perfect ;)
