### ISSUE TITLE
Attaching a role to show links.

### ISSUE THREAD

**Issue by ayyilmaz** [jslirola/flarum-ext-login2seeplus#22]
How can we attach a role to show links? I need to show links for only moderators or another user role? I will show the links verified users if it is possible.

**Comment by jslirola** [comment]
You could use this extension:
https://discuss.flarum.org/d/30167-login2see-add-bbcode-login-to-see-content

IIt may not be what you're looking for, but your request is complicated to implement here.

I recommend that you create a Tag with read permissions for that role and in this way the publications contained therein will not be visible to anyone.
