### ISSUE TITLE
Login 2 See Plus - support beta 14

### ISSUE THREAD

**Issue by Unity4K** [jslirola/flarum-ext-login2seeplus#5]
hi Will there be updates for beta 14?

**Comment by jslirola** [comment]
Hi @Unity4K , for sure. 

Next weekend I hope to have enough time to update the extension and add support for beta 14.

Regards.

**Comment by Unity4K** [comment]
thanks Good luck with

**Comment by jslirola** [comment]
https://github.com/jslirola/flarum-ext-login2seeplus/releases/tag/v0.1.7

```
composer update jslirola/flarum-ext-login2seeplus
php flarum cache:clear
```

I think it's working now. I'll wait until you confirm to close this issue and post it to Flarum. ;)

**Comment by Unity4K** [comment]
thank you sir for the beta 14 update plugin works fine
